version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_dependency2 # tercera prueba contenedor
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - cicd
  dependency-track:
    image: dependencytrack/frontend
    container_name: dependency_track_service
    ports:
      - "8081:8080"
    networks:
      - cicd
volumes:
  jenkins_home: {}
networks:
  cicd: {}
